version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  fetcher:
    build:
      context: .
      dockerfile: Dockerfile.fetcher
    container_name: rust_fetcher
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - RUST_LOG=info
      - DATABASE_URL=postgres://user:password@db:5432/mydb
    volumes:
      - ./:/usr/src/app

volumes:
  pgdata:
