CREATE TABLE IF NOT EXISTS runners_saturation (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    rid BIGINT NOT NULL,
    name TEXT NOT NULL,
    busy BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL
);
